#! /bin/sh

chosen=$(printf "  Power Off\n  Restart\n  Suspend\n  Hibernate\n  Log Out\n  Lock" | rofi -dmenu -i -theme-str '@import "power.rasi"')

case "$chosen" in
	"  Power Off") loginctl poweroff ;;
	"  Restart") loginctl reboot ;;
	"  Suspend") systemctl suspend-then-hibernate ;;
	"  Hibernate") loginctl hibernate ;;
	"  Log Out") bspc quit ;;
	"  Lock") slock ;;
	*) exit 1 ;;
esac
